### ISSUE TITLE
Python 3.7 raises ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-feedstock#220]
Issue:

Seeing the following in [this build log]( https://travis-ci.org/nanshe-org/rank_filter/jobs/443244033 ) when building a package for Python 3.7 using the `conda-forge` package in `main` and [this code]( https://github.com/nanshe-org/rank_filter/tree/afc377162d304fddb15af7beda45f2975030c7aa ). Looks very similar to issue ( https://github.com/ContinuumIO/anaconda-issues/issues/6698 ).

```python
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools.command.build_ext import build_ext as _build_ext
  File "/home/travis/miniconda/conda-bld/rank_filter_1539877162908/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 25, in <module>
    get_config_var("LDSHARED")
  File "/home/travis/miniconda/conda-bld/rank_filter_1539877162908/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/distutils/sysconfig.py", line 534, in get_config_var
    return get_config_vars().get(name)
  File "/home/travis/miniconda/conda-bld/rank_filter_1539877162908/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/distutils/sysconfig.py", line 466, in get_config_vars
    func()
  File "/home/travis/miniconda/conda-bld/rank_filter_1539877162908/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/distutils/sysconfig.py", line 426, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'
```

<br/>
Environment (<code>conda list</code>):
<details>

<br>

Build:
```
    binutils_impl_linux-64: 2.31.1-h6176602_1       defaults   
    binutils_linux-64:      2.31.1-h6176602_3       defaults   
    bzip2:                  1.0.6-h470a237_2        conda-forge
    ca-certificates:        2018.10.15-ha4d7672_0   conda-forge
    cmake:                  3.12.3-h011004d_0       conda-forge
    curl:                   7.61.1-h74213dd_2       conda-forge
    expat:                  2.2.5-hfc679d8_2        conda-forge
    gcc_impl_linux-64:      7.3.0-habb00fd_1        defaults   
    gcc_linux-64:           7.3.0-h553295d_3        defaults   
    gxx_impl_linux-64:      7.3.0-hdf63c60_1        defaults   
    gxx_linux-64:           7.3.0-h553295d_3        defaults   
    krb5:                   1.16.1-hbb41f41_0       conda-forge
    libcurl:                7.61.1-hbdb9355_2       conda-forge
    libedit:                3.1.20170329-haf1bffa_1 conda-forge
    libgcc-ng:              8.2.0-hdf63c60_1        defaults   
    libssh2:                1.8.0-h5b517e9_2        conda-forge
    libstdcxx-ng:           8.2.0-hdf63c60_1        defaults   
    libuv:                  1.23.2-h470a237_0       conda-forge
    ncurses:                6.1-hfc679d8_1          conda-forge
    openssl:                1.0.2p-h470a237_1       conda-forge
    patchelf:               0.9-hfc679d8_2          conda-forge
    rhash:                  1.3.6-h470a237_1        conda-forge
    tk:                     8.6.8-ha92aebf_0        conda-forge
    xz:                     5.2.4-h470a237_1        conda-forge
    zlib:                   1.2.11-h470a237_3       conda-forge
```

Host:
```
    blas:            1.1-openblas                          conda-forge
    boost-cpp:       1.68.0-h3a22d5f_0                     conda-forge
    bzip2:           1.0.6-h470a237_2                      conda-forge
    ca-certificates: 2018.10.15-ha4d7672_0                 conda-forge
    certifi:         2018.10.15-py37_1000                  conda-forge
    cython:          0.29-py37hfc679d8_0                   conda-forge
    icu:             58.2-hfc679d8_0                       conda-forge
    libffi:          3.2.1-hfc679d8_5                      conda-forge
    libgcc-ng:       8.2.0-hdf63c60_1                      defaults   
    libgfortran:     3.0.0-1                               conda-forge
    libstdcxx-ng:    8.2.0-hdf63c60_1                      defaults   
    ncurses:         6.1-hfc679d8_1                        conda-forge
    numpy:           1.11.3-py37_blas_openblashb06ca3d_205 conda-forge [blas_openblas]
    openblas:        0.3.3-ha44fe06_1                      conda-forge
    openssl:         1.0.2p-h470a237_1                     conda-forge
    pip:             18.1-py37_1000                        conda-forge
    python:          3.7.0-h5001a0f_4                      conda-forge
    readline:        7.0-haf1bffa_1                        conda-forge
    setuptools:      40.4.3-py37_0                         conda-forge
    sqlite:          3.25.2-hb1c47c0_0                     conda-forge
    tk:              8.6.8-ha92aebf_0                      conda-forge
    wheel:           0.32.1-py37_0                         conda-forge
    xz:              5.2.4-h470a237_1                      conda-forge
    zlib:            1.2.11-h470a237_3                     conda-forge
```

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

<br>

Using `conda` version `4.5.11` from `conda-forge` in a Python 3.7 environment on Ubuntu 14.04.5 LTS (Trusty) 64-bit. More info available on request and/or in the log.

</details>

**Comment by jjhelmus** [comment]
The build+host environment is mixing the conda provided compilers with the `toolchain` Python.  This will not work, you need to match the compilers with either the Python from `defaults` or from the `gcc` label of conda-forge.

**Comment by jakirkham** [comment]
Good point. Will look into it. Thanks.

**Comment by jakirkham** [comment]
Any idea why this doesn't happen for other Python versions?

**Comment by jjhelmus** [comment]
The `toolchain` builds of python 3.6.6 and 2.7.15 are build without the [_CONDA_PYTHON_SYSCONFIG_NAME](https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0013-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch) patch, see #212 and #213.  The same should be done for the Python 3.7.0 `toolchain` build but I have not had the time to prepare a PR for this.

**Comment by jakirkham** [comment]
Ok, that makes sense. Thanks for clarifying.

**Comment by arunhpatil** [comment]
I am having a similar issue, I have installed Jupyter notebook first and then installed Jupyter lab, and when I was playing around with Scanpy, I got this issue. I found a similar issue here but couldn't find a solution anywhere else online. I will be glad to hear your suggestions, and please let me know if you need any further information. 

(base)  H231NS7:~$ python
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scanpy as sc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arun/miniconda3/lib/python3.8/site-packages/scanpy/__init__.py", line 15, in <module>
    from . import tools as tl
  File "/home/arun/miniconda3/lib/python3.8/site-packages/scanpy/tools/__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "/home/arun/miniconda3/lib/python3.8/site-packages/scanpy/preprocessing/__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "/home/arun/miniconda3/lib/python3.8/site-packages/scanpy/preprocessing/_recipes.py", line 11, in <module>
    from ._normalization import normalize_total
  File "/home/arun/miniconda3/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py", line 6, in <module>
    from sklearn.utils import sparsefuncs
  File "/home/arun/.local/lib/python3.8/site-packages/sklearn/__init__.py", line 80, in <module>
    from .base import clone
  File "/home/arun/.local/lib/python3.8/site-packages/sklearn/base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "/home/arun/.local/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/home/arun/.local/lib/python3.8/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "/home/arun/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 22, in <module>
    import joblib
  File "/home/arun/.local/lib/python3.8/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/arun/.local/lib/python3.8/site-packages/joblib/memory.py", line 16, in <module>
    import pydoc
  File "/home/arun/miniconda3/lib/python3.8/pydoc.py", line 366, in <module>
    class Doc:
  File "/home/arun/miniconda3/lib/python3.8/pydoc.py", line 396, in Doc
    def getdocloc(self, object, basedir=sysconfig.get_path('stdlib')):
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 521, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 511, in get_paths
    return _expand_vars(scheme, vars)
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 172, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 559, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 430, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'
```

Thank you,
Arun

**Comment by jakirkham** [comment]
Would suggest raising a new issue, @arunhpatil
