### ISSUE TITLE
Add Python 3.6.7 to win-64

### ISSUE THREAD

**Issue by tadeu** [conda-forge/python-feedstock#228]
From [this build](https://ci.appveyor.com/project/conda-forge/python-feedstock/builds/20557170) it seems that `python-3.6.7-he025d50_1001.tar.bz2` was correctly constructed but there was a problem with `anaconda upload` (called by `upload-package`):

```
upload_package .\ .\recipe .ci_support\%CONFIG%.yaml
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Adding in variants from .ci_support\win_c_compilervs2015cxx_compilervs2015vc14.yaml
Attempting to finalize metadata for python
Solving environment: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\upload_package-script.py", line 10, in <module>
    sys.exit(upload_package())
  File "C:\Miniconda36-x64\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniconda36-x64\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Miniconda36-x64\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Miniconda36-x64\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Miniconda36-x64\lib\site-packages\conda_forge_ci_setup\build_utils.py", line 82, in upload_package
    upload_or_check(recipe_root, owner, channel, [config_file])
  File "C:\Miniconda36-x64\lib\site-packages\conda_forge_ci_setup\upload_or_check_non_existence.py", line 135, in upload_or_check
    upload(token_fn, path, owner, channel)
  File "C:\Miniconda36-x64\lib\site-packages\conda_forge_ci_setup\upload_or_check_non_existence.py", line 65, in upload
    env=os.environ)
  File "C:\Miniconda36-x64\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpaamujzui\\binstar.token', 'upload', 'C:\\bld\\win-64\\python-3.6.7-he025d50_1001.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
```

(Just for reference: issue https://github.com/conda-forge/matplotlib-feedstock/issues/194)

**Comment by tadeu** [comment]
Unfortunately the two rebuilds ([1.0.481](https://ci.appveyor.com/project/conda-forge/python-feedstock/builds/21070238) and [1.0.482](https://ci.appveyor.com/project/conda-forge/python-feedstock/builds/21072900)) triggered in #228 didn't work with the same problem :/

We are going to need more help from @conda-forge/core. Could it be a problem with the token?

**Comment by jakirkham** [comment]
Think PR ( https://github.com/conda-forge/python-feedstock/pull/244 ) should fix this.

**Comment by jakirkham** [comment]
AppVeyor build for 3.6 now [passes]( https://ci.appveyor.com/project/conda-forge/python-feedstock/builds/22603365 ) and the Python 3.6.7 build for Windows is now deployed. :)

<img width="1552" alt="screen shot 2019-02-24 at 00 40 33" src="https://user-images.githubusercontent.com/3019665/53295602-dea93d00-37cc-11e9-8d17-3f0cd92bcb29.png">
