### ISSUE TITLE
ModuleNotFoundError: No module named 'win32file' when trying conda update --all

### ISSUE THREAD

**Issue by boumboum** [conda-forge/python-feedstock#233]
When I try to issue the command: conda update --all
I receive this error message:
```
Traceback (most recent call last):                                                            
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__            
    return func(*args, **kwargs)                                                              
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main                  
    exit_code = do_call(args, p)                                                              
  File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call      
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])                          
  File "C:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module                   
    return _bootstrap._gcd_import(name[level:], package, level)                               
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                             
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load                           
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                  
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                           
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module                     
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 9, in <module>         
    from .install import install                                                              
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 20, in <module>            
    from ..core.index import calculate_channel_urls, get_index                                
  File "C:\Anaconda3\lib\site-packages\conda\core\index.py", line 7, in <module>              
    from .package_cache_data import PackageCacheData                                          
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
                                                                                              
    from .path_actions import CacheUrlAction, ExtractPackageAction                            
  File "C:\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 11, in <module>      
    from .envs_manager import USER_ENVIRONMENTS_TXT_FILE, register_env, unregister_env        
  File "C:\Anaconda3\lib\site-packages\conda\core\envs_manager.py", line 9, in <module>       
    from .prefix_data import PrefixData                                                       
  File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 16, in <module>       
    from ..gateways.disk.create import write_as_json_to_file                                  
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 16, in <module>   
    from .delete import rm_rf                                                                 
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 18, in <module>   
    import win32file                                                                          
ModuleNotFoundError: No module named 'win32file'                                              
                                                                                              
During handling of the above exception, another exception occurred:                           
                                                                                              
Traceback (most recent call last):                                                            
  File "C:\Anaconda3\Scripts\conda-script.py", line 10, in <module>                           
    sys.exit(main())                                                                          
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 113, in main                  
    return conda_exception_handler(_main, *args)                                              
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1108, in conda_exception_han
dler                                                                                          
    return_value = exception_handler(func, *args, **kwargs)                                   
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 822, in __call__            
    return self.handle_exception(exc_val, exc_tb)                                             
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 862, in handle_exception    
    return self.handle_unexpected_exception(exc_val, exc_tb)                                  
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 873, in handle_unexpected_ex
ception                                                                                       
    self.print_unexpected_error_report(error_report)                                          
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 943, in print_unexpected_err
or_report                                                                                     
    from .cli.main_info import get_env_vars_str, get_main_info_str                            
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 24, in <module>          
    from ..core.envs_manager import env_name                                                  
  File "C:\Anaconda3\lib\site-packages\conda\core\envs_manager.py", line 9, in <module>       
    from .prefix_data import PrefixData                                                       
  File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 16, in <module>       
    from ..gateways.disk.create import write_as_json_to_file                                  
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 16, in <module>   
    from .delete import rm_rf                                                                 
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 18, in <module>   
    import win32file                                                                          
ModuleNotFoundError: No module named 'win32file' 
```

It was never happening before.

**Comment by isuruf** [comment]
This is a conda issue and not python.
