### ISSUE TITLE
conda-build crashes on this recipe.

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/python-feedstock#329]
Over:

```
TypeError: argument of type 'StrictUndefined' is not iterable
```

<details>

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/environ.py:425: UserWarning: The environment variable 'PY_INTERP_LINKAGE_NATURE' is undefined.
  UserWarning
/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/environ.py:425: UserWarning: The environment variable 'PY_INTERP_DEBUG' is undefined.
  UserWarning
Traceback (most recent call last):
  File "/home/sylvain/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2846, in build_tree
    bypass_env_check=True)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 830, in render_recipe
    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 736, in distribute_variants
    bypass_env_check=bypass_env_check)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 1023, in parse_until_resolved
    bypass_env_check=bypass_env_check)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 945, in parse_again
    bypass_env_check=bypass_env_check),
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 1534, in _get_contents
    rendered = template.render(environment=env)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sylvain/dev/conda-forge/python-feedstock/recipe/meta.yaml", line 19, in top-level template code
    patches:
TypeError: argument of type 'StrictUndefined' is not iterable
```
</details>

**Comment by mingwandroid** [comment]
Does removing https://github.com/conda-forge/python-feedstock/blob/master/recipe/conda_build_config.yaml fix it?

**Comment by SylvainCorlay** [comment]
Nope.

**Comment by isuruf** [comment]
Please don't ignore the issue template. We also need the conda build line you use.

**Comment by SylvainCorlay** [comment]
The issue comes from line 

`{% if 'conda-forge' not in channel_targets %}`

Removing it this fixes the problem.

**Comment by mingwandroid** [comment]
You need to ensure your conda_build_config.yaml defines that.

**Comment by isuruf** [comment]
As @mingwandroid you need to pass the `conda_build_config.yaml` fro `conda-forge-pinning` package or do `conda build recipe -m .ci_support/linux_target_platformlinux-64.yaml`

**Comment by SylvainCorlay** [comment]
Gotcha thanks!
