### ISSUE TITLE
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'

### ISSUE THREAD

**Issue by arunhpatil** [conda-forge/python-feedstock#584]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am having a similar issue [#issue-371600384](https://github.com/conda-forge/python-feedstock/issues/220#issue-371600384), I had installed Jupyter notebook first and then installed Jupyter lab, and when I was playing around with Scanpy, I got this issue. I found a similar issue here but couldn't find a solution anywhere else online. I will be glad to hear your suggestions, and please let me know if you need any further information.

```
Traceback (most recent call last):
  File "/home/arun/miniconda3/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _sysconfig
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/locations/_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/locations/base.py", line 16, in <module>
    site_packages: typing.Optional[str] = sysconfig.get_path("purelib")
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 521, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 511, in get_paths
    return _expand_vars(scheme, vars)
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 172, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 559, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 430, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'
```

### Installed packages

```shell
# packages in environment at /home/arun/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
alembic                   1.8.1                    pypi_0    pypi
anaconda-client           1.7.2                      py_0    conda-forge
anndata                   0.8.0              pyhd8ed1ab_1    conda-forge
annoy                     1.17.1                   pypi_0    pypi
anyio                     3.6.1              pyhd8ed1ab_1    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h0a891b7_2    conda-forge
arpack                    3.7.0                hdefa2d7_2    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
async-generator           1.10                     pypi_0    pypi
attrs                     22.1.0             pyh71513ae_1    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bbknn                     1.5.1                    pypi_0    pypi
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binutils_impl_linux-64    2.38                 h2a08ee3_1
binutils_linux-64         2.38.0               hc2dff05_0
biopython                 1.79             py38h0a891b7_2    conda-forge
blas                      2.116                  openblas    conda-forge
blas-devel                3.9.0           16_linux64_openblas    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               hd32f23e_0    conda-forge
bowtie                    1.3.1            py38h9d192eb_4    bioconda
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
brotlipy                  0.7.0           py38h0a891b7_1004    conda-forge
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
cattrs                    22.1.0                   pypi_0    pypi
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
certipy                   0.1.3                    pypi_0    pypi
cffi                      1.15.1           py38h74dc2b5_0
chardet                   5.0.0            py38h578d9bd_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     7.1.2                    py38_0    local
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
conda                     22.9.0           py38h578d9bd_1    conda-forge
conda-build               3.20.5           py38h924ce5b_0    conda-forge
conda-package-handling    1.9.0            py38h0a891b7_0    conda-forge
contourpy                 1.0.5            py38h43d8883_0    conda-forge
cryptography              37.0.4           py38h2b5fc30_0    conda-forge
curl                      7.83.1               h7bff187_0    conda-forge
cutadapt                  4.1              py38hbff2b2d_1    bioconda
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.32                  pypi_0    pypi
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.6.3            py38hfa26641_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dnaio                     0.9.1            py38hbff2b2d_1    bioconda
docutils                  0.19             py38h578d9bd_0    conda-forge
dunamai                   1.13.0                   pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
exceptiongroup            1.0.0rc9                 pypi_0    pypi
executing                 1.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.9                h27087fc_0    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fontconfig                2.14.0               hc2a2eb6_1    conda-forge
fonttools                 4.37.3           py38h0a891b7_0    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
future                    0.18.2           py38h578d9bd_5    conda-forge
gcc_impl_linux-64         11.2.0               h1234567_1
gcc_linux-64              11.2.0               h5c386dc_0
get_version               3.5.4              pyhd8ed1ab_0    conda-forge
gettext                   0.19.8.1          h27087fc_1009    conda-forge
gfortran_impl_linux-64    11.2.0               h1234567_1
gfortran_linux-64         11.2.0               hc2dff05_0
git                       2.37.3          pl5321h36853c3_0    conda-forge
glib                      2.69.1               h4ff587b_1
glob2                     0.7                        py_0    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gprofiler-official        1.0.0                    pypi_0    pypi
graphite2                 1.3.14               h295c915_1
greenlet                  1.1.2                    pypi_0    pypi
gxx_impl_linux-64         11.2.0               h1234567_1
gxx_linux-64              11.2.0               hc2dff05_0
h5py                      3.7.0           nompi_py38h045baee_101    conda-forge
harfbuzz                  4.3.0                hd55b92a_0
harmonypy                 0.0.6                    pypi_0    pypi
hdf5                      1.12.2          nompi_h2386368_100    conda-forge
htslib                    1.16                 h6bc39ce_0    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.10                     pypi_0    pypi
igraph                    0.9.11                   pypi_0    pypi
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py38h578d9bd_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.16.0             pyh210e3f2_0    conda-forge
ipython                   8.5.0              pyh41d4057_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.0.1                    pypi_0    pypi
isa-l                     2.30.0               ha770c72_4    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-telemetry         0.1.0                    pypi_0    pypi
jupyter_client            7.3.5              pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.4.0              pyhd8ed1ab_0    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              4.11.1           py38h578d9bd_0    conda-forge
jupyter_highlight_selected_word 0.2.0           py38h578d9bd_1005    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1            py38h578d9bd_2    conda-forge
jupyter_server            1.19.1             pyhd8ed1ab_0    conda-forge
jupyterhub                2.3.1                    pypi_0    pypi
jupyterlab                3.4.7              pyhd8ed1ab_0    conda-forge
jupyterlab-widgets        3.0.1                    pypi_0    pypi
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.15.2             pyhd8ed1ab_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py38h43d8883_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1
legacy-api-wrap           1.2                      pypi_0    pypi
leidenalg                 0.8.10                   pypi_0    pypi
libarchive                3.3.3             hddc7a2b_1008    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-devel_linux-64     11.2.0               h1234567_1
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
liblapacke                3.9.0           16_linux64_openblas    conda-forge
liblief                   0.12.2               h27087fc_0    conda-forge
libllvm11                 11.1.0               he0ac6c6_4    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.22               h6239696_0    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-devel_linux-64  11.2.0               h1234567_1
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.2.0                h85742a9_0
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.14               h74e7548_0
libxslt                   1.1.35               h4e12654_0
libzlib                   1.2.12               h166bdaf_3    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
llvmlite                  0.39.1           py38h38d86a4_0    conda-forge
louvain                   0.7.1                    pypi_0    pypi
lxml                      4.9.1            py38h0a891b7_0    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
mako                      1.2.1                    pypi_0    pypi
mamba                     0.7.0            py38hc157fb9_0    conda-forge
markupsafe                2.1.1            py38h0a891b7_1    conda-forge
matplotlib-base           3.6.0            py38hb021067_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mirge3                    0.0.6              pyh3252c3a_0    bioconda
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
natsort                   8.2.0              pyhd8ed1ab_0    conda-forge
nbautoexport              0.5.0              pyhd8ed1ab_0    conda-forge
nbclassic                 0.4.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.6.8              pyhd8ed1ab_0    conda-forge
nbconvert                 7.0.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.0.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.0.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.6.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
numba                     0.56.2           py38h9a4aae9_1    conda-forge
numexpr                   2.8.3           py38h97b1c41_100    conda-forge
numpy                     1.23.3           py38h3a7f9d9_0    conda-forge
oauthlib                  3.2.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.3.21          pthreads_h320a7e8_3    conda-forge
openpyxl                  3.0.10           py38h5eee18b_0    anaconda
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pamela                    1.0.0                    pypi_0    pypi
pandas                    1.5.0            py38h8f669ce_0    conda-forge
pandoc                    2.19.2               ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.50.7               h05da053_0
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patchelf                  0.15.0               h58526e2_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pbzip2                    1.1.13                        0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                hc3806b6_1    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pigz                      2.6                  h27826a3_0    conda-forge
pillow                    8.0.1            py38h70fbd49_0    conda-forge
pip                       22.2.2                   pypi_0    pypi
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
polars                    0.14.11                  pypi_0    pypi
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
psutil                    5.9.2            py38h0a891b7_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-lief                   0.12.2           py38hfa26641_0    conda-forge
pybiomart                 0.2.0                    pypi_0    pypi
pycosat                   0.6.3           py38h0a891b7_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.2           py38h0a891b7_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.7              pyh6c4a22f_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py38h0a891b7_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.7.0            py38hf632491_2    conda-forge
python                    3.8.5                h7579374_1    anaconda
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python-igraph             0.10.0           py38h3805f6d_1    conda-forge
python-isal               1.0.1            py38h0a891b7_0    conda-forge
python-json-logger        2.0.4                    pypi_0    pypi
python-libarchive-c       4.0              py38h578d9bd_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38h0a891b7_4    conda-forge
pyzmq                     24.0.1           py38hfc09fa9_0    conda-forge
qtconsole                 5.3.1                    pypi_0    pypi
qtpy                      2.2.0                    pypi_0    pypi
r-base                    4.2.0                h1ae530e_0    r
r-base64enc               0.1_3             r42h76d94ec_4    r
r-cli                     3.3.0             r42h884c59f_0    r
r-crayon                  1.5.1             r42h6115d3f_0    r
r-digest                  0.6.29            r42h884c59f_0    r
r-ellipsis                0.3.2             r42h76d94ec_0    r
r-evaluate                0.15              r42h6115d3f_0    r
r-fansi                   1.0.3             r42h76d94ec_0    r
r-fastmap                 1.1.0             r42h884c59f_0    r
r-glue                    1.6.2             r42h76d94ec_0    r
r-htmltools               0.5.2             r42h76d94ec_0    r
r-irdisplay               1.1               r42h6115d3f_0    r
r-irkernel                1.3                       r42_0    r
r-jsonlite                1.8.0             r42h76d94ec_0    r
r-lifecycle               1.0.1             r42h142f84f_0    r
r-pbdzmq                  0.3_7             r42h884c59f_0    r
r-pillar                  1.7.0             r42h6115d3f_0    r
r-repr                    1.1.4             r42h6115d3f_0    r
r-rlang                   1.0.2             r42h884c59f_0    r
r-utf8                    1.2.2             r42h76d94ec_0    r
r-uuid                    1.1_0             r42h76d94ec_0    r
r-vctrs                   0.4.1             r42h884c59f_0    r
readline                  8.1.2                h0f457ee_0    conda-forge
reportlab                 3.5.68           py38hadf75a6_1    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
requests-cache            0.9.6                    pypi_0    pypi
rich                      12.5.1             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h2f28480_2    conda-forge
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
ruamel_yaml               0.15.80         py38h0a891b7_1007    conda-forge
samtools                  1.15.1               h6899075_1    bioconda
scanpy                    1.4.6                    pypi_0    pypi
sccaf                     0.0.10                   pypi_0    pypi
scikit-learn              0.23.1           py38h3a94b23_0    conda-forge
scipy                     1.9.1            py38hea3f02b_0    conda-forge
seaborn                   0.12.0               hd8ed1ab_0    conda-forge
seaborn-base              0.12.0             pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.4.0             pyhd8ed1ab_0    conda-forge
setuptools-scm            7.0.5              pyhd8ed1ab_0    conda-forge
setuptools_scm            7.0.5                hd8ed1ab_0    conda-forge
shellingham               1.5.0              pyhd8ed1ab_0    conda-forge
sinfo                     0.3.1                      py_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    5.2.3              pyhd8ed1ab_0    conda-forge
sphinx-rtd-theme          0.5.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlalchemy                1.4.40                   pypi_0    pypi
sqlite                    3.39.3               h4ff8645_0    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.2           py38h71d37f0_0    conda-forge
stdlib-list               0.7.0                      py_2    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbb                       2021.6.0             h924138e_0    conda-forge
terminado                 0.16.0             pyh41d4057_0    conda-forge
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py38h0a891b7_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
typer                     0.6.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
umap-learn                0.5.3            py38h578d9bd_0    conda-forge
unicodedata2              14.0.0           py38h0a891b7_1    conda-forge
url-normalize             1.4.3                    pypi_0    pypi
urllib3                   1.25.11                  pypi_0    pypi
viennarna                 2.4.14           py38h8162308_3    bioconda
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.4.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.1                    pypi_0    pypi
xopen                     1.6.0            py38h578d9bd_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_3    conda-forge
zstd                      1.4.5                h9ceee32_0
```

### Environment info

```shell
/home/arun/.local/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.11) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

     active environment : base
    active env location : /home/arun/miniconda3
            shell level : 1
       user config file : /home/arun/.condarc
 populated config files : /home/arun/.condarc
          conda version : 22.9.0
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/arun/miniconda3  (writable)
      conda av data dir : /home/arun/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/arun/miniconda3/pkgs
                          /home/arun/.conda/pkgs
       envs directories : /home/arun/miniconda3/envs
                          /home/arun/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.23.0 CPython/3.8.5 Linux/4.4.0-19041-Microsoft ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by isuruf** [comment]
Your python comes from anaconda and not conda-forge. Please only report problems with conda-forge packages here.
```
python                    3.8.5                h7579374_1    anaconda
```
